Resources:
  CognitoAuthorizedApiPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CognitoAuthorizedApiPolicy-${self:custom.resourcePrefix}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "execute-api:Invoke"
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:execute-api:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - ":"
                  - Ref: ApiGatewayRestApi
                  - "/*"
          - Effect: "Allow"
            Action:
              - "s3:PutObject"
            Resource:
              # Allow users to upload to the uploads area
              - Fn::Join:
                  - ""
                  - - "Fn::ImportValue": ${self:custom.resourcePrefix}-ExtAttachmentsBucketArn
                    - "/uploads/*"
      Roles:
        - "Fn::ImportValue": ${self:custom.resourcePrefix}-ExtCognitoAuthRole
